### ISSUE TITLE
Add a paper to the publication page

### ISSUE THREAD

**Issue by shieldsca** [brmy4086/ARTMIP#6]
I tried to do this myself, but I was not sure if it was OK add a "fork" -- I think I will need further instruction!  In the meantime, can you add this to 2024?

Reiher, C. A., and A. C. Winters, 2024: Discriminating Factors that Favor the Development of High-Impact Weather Events in Association with Polar–Subtropical Jet Superpositions. Mon. Wea. Rev., 152, 909–924, https://doi.org/10.1175/MWR-D-23-0061.1.

I've added it to the current webpage already at the top...  thanks!

**Comment by brmy4086** [comment]
I can explain things better in person about "forking" and "branches", but doing that won't change anything on the actual page (just for your version of the code, not the main version). I think you still need to accept my invite to be a collaborator before it will allow you to change things in the main version. I'll add this now!

**Comment by shieldsca** [comment]
Ok! I didn't realize I hadn't accepted the invite yet!  Just did -- ok, you can explain things next meeting :) Thanks!
